enabled_locales: ["en", "vi"]
client:
  host: "localhost:3000"
users:
  name:
    maximum: 50
  email:
    maximum: 255
  password:
    minimum: 6
remember: "1"
gravatar_for:
  size: 50
perpage: 9
time_exists: 1
