enabled_locales: ["en", "vi"]
client:
  host: "localhost:3000"
users:
  name:
    maximum: 50
  email:
    maximum: 255
  password:
    minimum: 6
remember: "1"
gravatar_for:
  size: 50
perpage: 7
time_exists: 1
micropost:
  content:
    maximum: 140
max_size_picture: 5
accept_picture: "image/jpeg,image/gif,image/png"
gravatar_follow:
  size: 30
